// NOTE
export const NOTE_CREATE = 'NOTE_CREATE'
export const NOTE_SAVE = 'NOTE_SAVE'
export const NOTE_DELETE = 'NOTE_DELETE'
// NOTE EDITOR
export const NOTE_EDITOR_OPEN = 'NOTE_EDITOR_OPEN'
export const NOTE_EDITOR_CLOSE = 'NOTE_EDITOR_CLOSE'
// NOTE OPENED
export const NOTE_KEY_ADD = 'NOTE_KEY_ADD'
export const NOTE_KEY_EDIT = 'NOTE_KEY_EDIT'
export const NOTE_KEY_UPDATE = 'NOTE_KEY_UPDATE'
export const NOTE_KEY_SAVE = 'NOTE_KEY_SAVE'
export const NOTE_KEY_RESET = 'NOTE_KEY_RESET'
export const NOTE_KEY_DELETE = 'NOTE_KEY_DELETE'
